### ISSUE TITLE
/roll 3d6+3 ... not valid die code ...

### ISSUE THREAD

**Issue by Umbyology** [Taffer/ca.taffer.mm-rolly#13]
I get the following message ... '3d6+3' is not a valid die code See `/roll help` for examples.

Suggestions?

I just installed the latest version of Mattermost ...

Mattermost Version: 5.15.0
Database Schema Version: 5.15.0
Database: postgres

**Comment by Taffer** [comment]
I just tried `/roll 3d6+3` on our install and it works fine; we're still on 5.14, but I doubt that's the problem.

Could you add a screen shot of the error?

![Annotation 2019-09-27 063412](https://user-images.githubusercontent.com/1213088/65763219-e6c5b400-e0f0-11e9-8bc8-f8144bee4994.png)

**Comment by Umbyology** [comment]
Regular dice expressions work until I add a modifier of some kind (-/+).

<img width="1277" alt="Screen Shot 2019-09-27 at 9 55 29 PM" src="https://user-images.githubusercontent.com/22547499/65810607-02bd6a00-e172-11e9-98db-dbc7318a0c58.png">

![IMG_0874](https://user-images.githubusercontent.com/22547499/65810611-05b85a80-e172-11e9-8004-adc0c4641d36.png)

**Comment by Taffer** [comment]
What language settings have you got? I'm wondering if I need to expand my regex to account for Unicode... I've only tested this with English, unfortunately.

**Comment by Taffer** [comment]
"not a valid die code" doesn't actually appear in the current code; can you make sure you're running the latest release? It should be 1.1.

**Comment by Umbyology** [comment]
> What language settings have you got? I'm wondering if I need to expand my regex to account for Unicode... I've only tested this with English, unfortunately.

My Localization default languages are both set to English. Also, this is a fresh/clean install of Mattermost. I done no changes, modifications or odd-ball settings other than a few standard plugins and yours.

**Comment by Umbyology** [comment]
> "not a valid die code" doesn't actually appear in the current code; can you make sure you're running the latest release? It should be 1.1.
> 
> Version 1.1 says something like this when it can't parse the `/roll`:

Wow! ... glad you asked. I have a different dice plugin installed, it is not yours at all ... DOH! Damn it, damn it, damn it, damn it, damn it, damn it, damn it, damn it, damn it ;)

The end.

**Comment by Taffer** [comment]
😄 No worries, glad we figured it out!
