### ISSUE TITLE
Plugin failed to start

### ISSUE THREAD

**Issue by Umbyology** [Taffer/ca.taffer.mm-rolly#15]
Greetings, new issue here.

I downloaded v1.1 release and uploaded via the System Console. Upload is good, but when I enabled the plugin I get the following error ...

"This plugin failed to start. Check your system logs for errors."

In order I tried the following ... disabled the plugin and re-enabled it; no change. I restarted the server; no change. Removed the plugin, re-uploaded it, refreshed the page, enabled the plugin; no change.

Suggestions?

<img width="548" alt="Screen Shot 2019-09-28 at 11 57 05 AM" src="https://user-images.githubusercontent.com/22547499/65819879-5fa73780-e1e7-11e9-982c-4760c99788eb.png">

**Comment by Umbyology** [comment]
Here are the logs ...

`{"level":"error","ts":1569689232.380515,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-r
{"level":"warn","ts":1569689232.4161444,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689232.4162807,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"warn","ts":1569689232.4233131,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689232.4234295,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"info","ts":1569689676.2624242,"caller":"utils/i18n.go:83","msg":"Loaded system translations for 'en' from '/mattermost/i18n/en.json'"}                                     
{"level":"info","ts":1569689676.2641819,"caller":"app/server_app_adapters.go:58","msg":"Server is initializing..."}                                                                  
{"level":"info","ts":1569689676.2761767,"caller":"sqlstore/supplier.go:223","msg":"Pinging SQL master database"}                                                                     
{"level":"info","ts":1569689677.341793,"caller":"mlog/log.go:165","msg":"Starting up plugins"}                                                                                       
{"level":"info","ts":1569689677.3419764,"caller":"app/plugin.go:195","msg":"Syncing plugins from the file store"}                                                                    
{"level":"info","ts":1569689677.4743743,"caller":"app/plugin.go:248","msg":"Syncing plugin from file store","bundle":"plugins/ca.taffer.mm-rolly.tar.gz"}                            
{"level":"warn","ts":1569689679.3097217,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689679.3212364,"caller":"app/plugin.go:250","msg":"Failed to sync plugin from file store","bundle":"plugins/ca.taffer.mm-rolly.tar.gz","error":"installPlug
{"level":"warn","ts":1569689683.1394665,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689683.1397796,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"info","ts":1569689683.141974,"caller":"app/server.go:216","msg":"Current version is 5.15.0 (5.15.0/Mon Sep 16 19:14:33 UTC 2019/f4f7fd0829d74fcd5e290fd1ba76845af18e553e/no
{"level":"info","ts":1569689683.142,"caller":"app/server.go:217","msg":"Enterprise Enabled: false"}                                                                                  
{"level":"info","ts":1569689683.1420214,"caller":"app/server.go:219","msg":"Current working directory is /mattermost"}                                                               
{"level":"info","ts":1569689683.1420326,"caller":"app/server.go:220","msg":"Loaded config","source":"file:///mattermost/config/config.json"}                                         
{"level":"warn","ts":1569689683.1724684,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689683.1728108,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"info","ts":1569689683.2013724,"caller":"sqlstore/post_store.go:1301","msg":"Post.Message supports at most 16383 characters (65535 bytes)"}                                 
{"level":"warn","ts":1569689683.204288,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                              
{"level":"error","ts":1569689683.204467,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-r
{"level":"warn","ts":1569689683.27374,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                               
{"level":"error","ts":1569689683.2739475,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"warn","ts":1569689683.2807248,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569689683.2812722,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"info","ts":1569689683.2871168,"caller":"jobs/workers.go:68","msg":"Starting workers"}                                                                                      
{"level":"info","ts":1569689683.2872088,"caller":"app/server.go:423","msg":"Starting Server..."}                                                                                     
{"level":"info","ts":1569689683.2872243,"caller":"app/server.go:449","msg":"RateLimiter is enabled"}                                                                                 
{"level":"info","ts":1569689683.2880583,"caller":"app/server.go:489","msg":"Server is listening on [::]:8000"}                                                                       
{"level":"info","ts":1569689683.3127265,"caller":"jobs/schedulers.go:72","msg":"Starting schedulers."}                                                                               
{"level":"info","ts":1569689683.3229659,"caller":"app/web_hub.go:75","msg":"Starting 2 websocket hubs"}                                                                              
{"level":"warn","ts":1569690126.3033285,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569690126.305203,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-r
{"level":"warn","ts":1569690126.319532,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                              
{"level":"error","ts":1569690126.3201642,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"warn","ts":1569690126.3894484,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                             
{"level":"error","ts":1569690126.3896618,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-
{"level":"warn","ts":1569690126.398281,"caller":"plugin/hclog_adapter.go:53","msg":"plugin failed to exit gracefully","plugin_id":"ca.taffer.mm-rolly"}                              
{"level":"error","ts":1569690126.3985023,"caller":"mlog/log.go:173","msg":"Unable to activate plugin","plugin_id":"ca.taffer.mm-rolly","error":"unable to start plugin: ca.taffer.mm-`

**Comment by Taffer** [comment]
Hmm, those aren't too helpful... it looks like we're not even getting into my code at all.

What platform is your server running on? I've only tested this with a server running on Ubuntu 18.04 LTS...

**Comment by Taffer** [comment]
This ended up being user error.
